Fotran EDRIXS: ed_driver.f90 File Reference
ed_driver.f90 File Reference
Functions/Subroutines
subroutine ed_driver ()
This sets up the drive for calling the ED code.
.
Function/Subroutine Documentation
ed_driver()
subroutine ed_driver
This sets up the drive for calling the ED code.
.
Here we initialiaze a few definition used in the work for for a cluster:
\(s_i \): Index for site \(-i\)
\(| F \rangle = \Pi_i |s_i\rangle \): Fock state configuration
\(| F \rangle = \{| F_n \rangle \}\): Fock space
\(H = H^T + H^C \): Hamiltonian
\(N \): Size of Fock space = Dimention of \(H\)
\(h_{ij}^T, h_{ij}^C\) : Hopping table, Coulomb table
Read \(\langle s_j|h_{ij}^T |s_i\rangle \), \(\langle s_j |h_{ij}^C |s_i\rangle \) and \(|F\rangle \) from io.f90 file
Build \(H \) by calling build_ham_i from ham.f90
Calls ED solver:
ed_solver = 0 : full ED using full_diag.f90
ed_solver = 1 : Lanczos from anczos.f90
ed_solver = 2 : Arpack from arpack.f90
\(E_i\); Eigenvalue with index- \(i\)
\(|V_i\rangle = \sum_n a_n^i |F_n\rangle \) : Eigenvector with index- \(i\)
Evaluate Density Matrix given by:
\(M_{ij} = |s_i\rangle \langle s_| KK x \)
Definition at line 22 of file ed_driver.f90.
References m_global::alloc_ham_csr(), binary_search(), build_ham_i(), m_global::coulomb_i, m_types::csr_to_full(), m_constants::czero, m_global::dealloc_coulomb_i(), m_global::dealloc_fock_i(), m_global::dealloc_ham_csr(), m_global::dealloc_hopping_i(), diag_ham_arpack(), m_lanczos::diag_ham_lanczos(), m_control::ed_solver, m_control::eigval_tol, m_global::fock_i, full_diag_ham(), get_needed_indx(), get_number_nonzeros(), m_global::ham_csr, m_global::hopping_i, m_control::idump, make_newfock(), m_control::master, m_control::maxiter, m_control::min_ndim, m_control::myid, m_constants::mystd, m_control::ncoul_i, m_control::ncv, m_control::ndim_i, m_control::neval, m_control::new_comm, m_control::nhopp_i, partition_task(), read_coulomb_i(), read_fock_i(), read_hopping_i(), write_denmat(), write_eigvecs(), write_lowest_eigvals(), and m_constants::zero.