Fotran EDRIXS: ed_main.f90 File Reference
ed_main.f90 File Reference
Functions/Subroutines
program ed_main
Function/Subroutine Documentation
ed_main()
program ed_main
This is main program that initializes the fortran code and calls the ed_driver.
One can control the various flags from the m_control file.
From io.f90 file, it calls
config: Gives dimension of the matrix
read_fock_i: Provides fock basis by reading fock_i.in file
Deallocates dealloc_fock_i from m_global file
Call ed_driver.f90
Definition at line 10 of file ed_main.f90.
References config(), m_global::dealloc_fock_i(), ed_driver(), m_control::master, m_control::myid, m_control::ndim_i, m_control::new_comm, m_control::nprocs, m_control::origin_comm, m_control::origin_myid, m_control::origin_nprocs, and read_fock_i().