Fotran EDRIXS: ham.f90 File Reference
ham.f90 File Reference
Functions/Subroutines
subroutine build_ham_i (ncfgs, fock, nblock, end_indx, nhopp, hopping, ncoul, coulomb, omega, ham_sign, ham_csr)
Using the \(h_{ij}^T, h_{ij}^C\) table, this generates \(H\) in the Fock space.
Generates the transition operators, \(D_{i}|g\rangle \).
subroutine build_ham_n (ncfgs, fock, num_val_orbs, num_core_orbs, nblock, end_indx, nhopp, hopping, ncoul, coulomb, omega, ham_sign, ham_csr)
subroutine build_transop_i (mcfgs, ncfgs, fock_left, fock_right, num_val_orbs, num_core_orbs, nblock, end_indx, ntran, transop, tran_csr)
subroutine build_transop_f (mcfgs, ncfgs, fock_left, fock_right, num_val_orbs, num_core_orbs, nblock, end_indx, ntran, transop, tran_csr)
Function/Subroutine Documentation
build_ham_i()
subroutine build_ham_i (integer, intent(in) ncfgs, integer(dp), dimension(ncfgs), intent(in) fock, integer, intent(in) nblock, integer, dimension(2,2,nprocs), intent(in) end_indx, integer, intent(in) nhopp, type (t_tensor2), dimension(nhopp), intent(in) hopping, integer, intent(in) ncoul, type (t_tensor4), dimension(ncoul), intent(in) coulomb, complex(dp), intent(in) omega, real(dp), intent(in) ham_sign, type (t_csr), dimension(nblock) ham_csr)
Using the \(h_{ij}^T, h_{ij}^C\) table, this generates \(H\) in the Fock space.
Generates the transition operators, \(D_{i}|g\rangle \).
Definition at line 6 of file ham.f90.
References m_types::alloc_csr(), binary_search(), m_constants::dp, m_types::init_col(), m_types::insert_into_row(), make_newfock(), m_control::master, m_control::myid, and m_control::nprocs.
build_ham_n()
subroutine build_ham_n (integer, intent(in) ncfgs, integer(dp), dimension(ncfgs), intent(in) fock, integer, intent(in) num_val_orbs, integer, intent(in) num_core_orbs, integer, intent(in) nblock, integer, dimension(2,2,nprocs), intent(in) end_indx, integer, intent(in) nhopp, type (t_tensor2), dimension(nhopp), intent(in) hopping, integer, intent(in) ncoul, type (t_tensor4), dimension(ncoul), intent(in) coulomb, complex(dp), intent(in) omega, real(dp), intent(in) ham_sign, type (t_csr), dimension(nblock) ham_csr)
Definition at line 356 of file ham.f90.
References m_types::alloc_csr(), binary_search(), m_constants::dp, m_types::init_col(), m_types::insert_into_row(), make_newfock(), m_control::master, m_control::myid, and m_control::nprocs.
build_transop_f()
subroutine build_transop_f (integer, intent(in) mcfgs, integer, intent(in) ncfgs, integer(dp), dimension(mcfgs), intent(in) fock_left, integer(dp), dimension(ncfgs), intent(in) fock_right, integer, intent(in) num_val_orbs, integer, intent(in) num_core_orbs, integer, intent(in) nblock, integer, dimension(2,2,nprocs), intent(in) end_indx, integer, intent(in) ntran, type(t_tensor2), dimension(ntran), intent(in) transop, type (t_csr), dimension(nblock) tran_csr)
Definition at line 919 of file ham.f90.
References m_types::alloc_csr(), binary_search(), m_constants::dp, m_types::init_col(), m_types::insert_into_row(), make_newfock(), m_control::myid, and m_control::nprocs.
build_transop_i()
subroutine build_transop_i (integer, intent(in) mcfgs, integer, intent(in) ncfgs, integer(dp), dimension(mcfgs), intent(in) fock_left, integer(dp), dimension(ncfgs), intent(in) fock_right, integer, intent(in) num_val_orbs, integer, intent(in) num_core_orbs, integer, intent(in) nblock, integer, dimension(2,2,nprocs), intent(in) end_indx, integer, intent(in) ntran, type(t_tensor2), dimension(ntran), intent(in) transop, type (t_csr), dimension(nblock) tran_csr)
Definition at line 718 of file ham.f90.
References m_types::alloc_csr(), binary_search(), m_constants::dp, m_types::init_col(), m_types::insert_into_row(), make_newfock(), m_control::myid, and m_control::nprocs.