Fotran EDRIXS: io.f90 File Reference
io.f90 File Reference
Functions/Subroutines
subroutine config ()
config: Reads control parameters from config.in file on master node and broadcastes it to all nodes
read_hopping_i: Reads the hopping matrix from hopping_i.in file
read_coulomb_i: Reads the coulumb matrix from coulumb_i.in file
read_fock_i: Reads the coulumb matrix from coulumb_i.in file
subroutine read_hopping_i ()
subroutine read_coulomb_i ()
subroutine read_fock_i ()
subroutine read_hopping_n ()
subroutine read_coulomb_n ()
subroutine read_fock_n ()
subroutine read_fock_f ()
subroutine read_transop_xas ()
subroutine read_transop_rixs_i ()
subroutine read_transop_rixs_f ()
subroutine write_krylov (fname, neff, alpha, beta, norm, e_gs)
subroutine write_eigvecs (fname, nloc, eigvec, eigval)
subroutine read_eigvecs (fname, nloc, eigvec, eigval)
subroutine write_lowest_eigvals (n, eigval)
subroutine write_denmat (n, num_orbs, denmat)
subroutine write_opavg (n, eval, opavg)
Function/Subroutine Documentation
config()
subroutine config
config: Reads control parameters from config.in file on master node and broadcastes it to all nodes
read_hopping_i: Reads the hopping matrix from hopping_i.in file
read_coulomb_i: Reads the coulumb matrix from coulumb_i.in file
read_fock_i: Reads the coulumb matrix from coulumb_i.in file
Definition at line 6 of file io.f90.
References m_control::ed_solver, m_control::eigval_tol, m_control::gamma_in, m_control::idump, m_control::linsys_max, m_control::linsys_tol, m_control::master, m_control::maxiter, m_control::min_ndim, m_constants::mystd, m_constants::mytmp, m_control::ncv, m_control::neval, m_control::nkryl, m_control::num_core_orbs, m_control::num_gs, m_control::num_val_orbs, m_control::nvector, m_control::omega_in, m_control::origin_comm, and m_control::origin_myid.
read_coulomb_i()
subroutine read_coulomb_i
Definition at line 124 of file io.f90.
References m_global::alloc_coulomb_i(), m_global::coulomb_i, m_constants::dp, m_control::master, m_control::myid, m_constants::mystd, m_constants::mytmp, m_control::ncoul_i, and m_control::new_comm.
read_coulomb_n()
subroutine read_coulomb_n
Definition at line 257 of file io.f90.
References m_global::alloc_coulomb_n(), m_global::coulomb_n, m_constants::dp, m_control::master, m_control::myid, m_constants::mystd, m_constants::mytmp, m_control::ncoul_n, and m_control::new_comm.
read_eigvecs()
subroutine read_eigvecs (character(*), intent(in) fname, integer, intent(in) nloc, complex(dp), dimension(nloc), intent(out) eigvec, real(dp), intent(out) eigval)
Definition at line 567 of file io.f90.
References m_constants::dp, m_control::myid, and m_constants::mytmp.
read_fock_f()
subroutine read_fock_f
Definition at line 340 of file io.f90.
References m_global::alloc_fock_f(), m_global::fock_f, m_constants::mystd, m_constants::mytmp, and m_control::ndim_f.
read_fock_i()
subroutine read_fock_i
Definition at line 178 of file io.f90.
References m_global::alloc_fock_i(), m_global::fock_i, m_constants::mystd, m_constants::mytmp, and m_control::ndim_i.
read_fock_n()
subroutine read_fock_n
Definition at line 312 of file io.f90.
References m_global::alloc_fock_n(), m_global::fock_n, m_constants::mystd, m_constants::mytmp, and m_control::ndim_n_nocore.
read_hopping_i()
subroutine read_hopping_i
Definition at line 74 of file io.f90.
References m_global::alloc_hopping_i(), m_constants::dp, m_global::hopping_i, m_control::master, m_control::myid, m_constants::mystd, m_constants::mytmp, m_control::new_comm, and m_control::nhopp_i.
read_hopping_n()
subroutine read_hopping_n
Definition at line 206 of file io.f90.
References m_global::alloc_hopping_n(), m_constants::dp, m_global::hopping_n, m_control::master, m_control::myid, m_constants::mystd, m_constants::mytmp, m_control::new_comm, and m_control::nhopp_n.
read_transop_rixs_f()
subroutine read_transop_rixs_f
Definition at line 469 of file io.f90.
References m_global::alloc_transop_rixs_f(), m_constants::dp, m_control::master, m_control::myid, m_constants::mystd, m_constants::mytmp, m_control::new_comm, m_control::ntran_rixs_f, and m_global::transop_rixs_f.
read_transop_rixs_i()
subroutine read_transop_rixs_i
Definition at line 418 of file io.f90.
References m_global::alloc_transop_rixs_i(), m_constants::dp, m_control::master, m_control::myid, m_constants::mystd, m_constants::mytmp, m_control::new_comm, m_control::ntran_rixs_i, and m_global::transop_rixs_i.
read_transop_xas()
subroutine read_transop_xas
Definition at line 368 of file io.f90.
References m_global::alloc_transop_xas(), m_constants::dp, m_control::master, m_control::myid, m_constants::mystd, m_constants::mytmp, m_control::new_comm, m_control::ntran_xas, and m_global::transop_xas.
write_denmat()
subroutine write_denmat (integer, intent(in) n, integer, intent(in) num_orbs, complex(dp), dimension(num_orbs, num_orbs, n), intent(in) denmat)
Definition at line 614 of file io.f90.
References m_constants::dp, m_control::master, m_control::myid, and m_constants::mytmp.
write_eigvecs()
subroutine write_eigvecs (character(*), intent(in) fname, integer, intent(in) nloc, complex(dp), dimension(nloc), intent(in) eigvec, real(dp), intent(in) eigval)
Definition at line 548 of file io.f90.
References m_constants::dp, and m_constants::mytmp.
write_krylov()
subroutine write_krylov (character(*), intent(in) fname, integer, intent(in) neff, real(dp), dimension(neff), intent(in) alpha, real(dp), dimension(neff), intent(in) beta, real(dp), intent(in) norm, real(dp), intent(in) e_gs)
Definition at line 519 of file io.f90.
References m_constants::dp, m_control::master, m_control::myid, and m_constants::mytmp.
write_lowest_eigvals()
subroutine write_lowest_eigvals (integer, intent(in) n, real(dp), dimension(n), intent(in) eigval)
Definition at line 591 of file io.f90.
References m_constants::dp, m_control::master, m_control::myid, and m_constants::mytmp.
write_opavg()
subroutine write_opavg (integer, intent(in) n, real(dp), dimension(n), intent(in) eval, complex(dp), dimension(n), intent(in) opavg)
Definition at line 642 of file io.f90.
References m_constants::dp, m_control::master, m_control::myid, and m_constants::mytmp.