Fotran EDRIXS: m_global Module Reference
m_global Module Reference
Functions/Subroutines
subroutine alloc_hopping_i ()
subroutine dealloc_hopping_i ()
subroutine alloc_coulomb_i ()
subroutine dealloc_coulomb_i ()
subroutine alloc_fock_i ()
subroutine dealloc_fock_i ()
subroutine alloc_hopping_n ()
subroutine dealloc_hopping_n ()
subroutine alloc_coulomb_n ()
subroutine dealloc_coulomb_n ()
subroutine alloc_fock_n ()
subroutine dealloc_fock_n ()
subroutine alloc_fock_f ()
subroutine dealloc_fock_f ()
subroutine alloc_transop_xas ()
subroutine dealloc_transop_xas ()
subroutine alloc_transop_rixs_i ()
subroutine dealloc_transop_rixs_i ()
subroutine alloc_transop_rixs_f ()
subroutine dealloc_transop_rixs_f ()
subroutine alloc_ham_csr (nblock)
subroutine dealloc_ham_csr (nblock)
subroutine alloc_tran_csr (nblock)
subroutine dealloc_tran_csr (nblock)
Variables
type(t_tensor2), dimension(:), allocatable, save, public hopping_i
type(t_tensor4), dimension(:), allocatable, save, public coulomb_i
type(t_tensor2), dimension(:), allocatable, save, public hopping_n
type(t_tensor4), dimension(:), allocatable, save, public coulomb_n
type(t_tensor2), dimension(:), allocatable, save, public transop_xas
type(t_tensor2), dimension(:), allocatable, save, public transop_rixs_i
type(t_tensor2), dimension(:), allocatable, save, public transop_rixs_f
integer(dp), dimension(:), allocatable, save, public fock_i
integer(dp), dimension(:), allocatable, save, public fock_n
integer(dp), dimension(:), allocatable, save, public fock_f
type(t_csr), dimension(:), allocatable, save, public ham_csr
type(t_csr), dimension(:), allocatable, save, public tran_csr
real(dp), dimension(:), allocatable, save, public krylov_alpha
real(dp), dimension(:), allocatable, save, public krylov_beta
Function/Subroutine Documentation
alloc_coulomb_i()
subroutine m_global::alloc_coulomb_i
Definition at line 63 of file m_global.f90.
References coulomb_i, m_constants::czero, and m_control::ncoul_i.
alloc_coulomb_n()
subroutine m_global::alloc_coulomb_n
Definition at line 136 of file m_global.f90.
References coulomb_n, m_constants::czero, and m_control::ncoul_n.
alloc_fock_f()
subroutine m_global::alloc_fock_f
Definition at line 183 of file m_global.f90.
References fock_f, and m_control::ndim_f.
alloc_fock_i()
subroutine m_global::alloc_fock_i
Definition at line 91 of file m_global.f90.
References fock_i, and m_control::ndim_i.
alloc_fock_n()
subroutine m_global::alloc_fock_n
Definition at line 164 of file m_global.f90.
References fock_n, and m_control::ndim_n_nocore.
alloc_ham_csr()
subroutine m_global::alloc_ham_csr (integer, intent(in) nblock)
Definition at line 281 of file m_global.f90.
References ham_csr, and m_types::init_csr().
alloc_hopping_i()
subroutine m_global::alloc_hopping_i
Definition at line 37 of file m_global.f90.
References m_constants::czero, hopping_i, and m_control::nhopp_i.
alloc_hopping_n()
subroutine m_global::alloc_hopping_n
Definition at line 110 of file m_global.f90.
References m_constants::czero, hopping_n, and m_control::nhopp_n.
alloc_tran_csr()
subroutine m_global::alloc_tran_csr (integer, intent(in) nblock)
Definition at line 311 of file m_global.f90.
References m_types::init_csr(), and tran_csr.
alloc_transop_rixs_f()
subroutine m_global::alloc_transop_rixs_f
Definition at line 255 of file m_global.f90.
References m_constants::czero, m_control::ntran_rixs_f, and transop_rixs_f.
alloc_transop_rixs_i()
subroutine m_global::alloc_transop_rixs_i
Definition at line 229 of file m_global.f90.
References m_constants::czero, m_control::ntran_rixs_i, and transop_rixs_i.
alloc_transop_xas()
subroutine m_global::alloc_transop_xas
Definition at line 202 of file m_global.f90.
References m_constants::czero, m_control::ntran_xas, and transop_xas.
dealloc_coulomb_i()
subroutine m_global::dealloc_coulomb_i
Definition at line 83 of file m_global.f90.
References coulomb_i.
dealloc_coulomb_n()
subroutine m_global::dealloc_coulomb_n
Definition at line 156 of file m_global.f90.
References coulomb_n.
dealloc_fock_f()
subroutine m_global::dealloc_fock_f
Definition at line 194 of file m_global.f90.
References fock_f.
dealloc_fock_i()
subroutine m_global::dealloc_fock_i
Definition at line 102 of file m_global.f90.
References fock_i.
dealloc_fock_n()
subroutine m_global::dealloc_fock_n
Definition at line 175 of file m_global.f90.
References fock_n.
dealloc_ham_csr()
subroutine m_global::dealloc_ham_csr (integer, intent(in) nblock)
Definition at line 296 of file m_global.f90.
References m_types::dealloc_csr(), and ham_csr.
dealloc_hopping_i()
subroutine m_global::dealloc_hopping_i
Definition at line 55 of file m_global.f90.
References hopping_i.
dealloc_hopping_n()
subroutine m_global::dealloc_hopping_n
Definition at line 128 of file m_global.f90.
References hopping_n.
dealloc_tran_csr()
subroutine m_global::dealloc_tran_csr (integer, intent(in) nblock)
Definition at line 326 of file m_global.f90.
References m_types::dealloc_csr(), and tran_csr.
dealloc_transop_rixs_f()
subroutine m_global::dealloc_transop_rixs_f
Definition at line 273 of file m_global.f90.
References transop_rixs_f.
dealloc_transop_rixs_i()
subroutine m_global::dealloc_transop_rixs_i
Definition at line 247 of file m_global.f90.
References transop_rixs_i.
dealloc_transop_xas()
subroutine m_global::dealloc_transop_xas
Definition at line 220 of file m_global.f90.
References transop_xas.
Variable Documentation
coulomb_i
type(t_tensor4), dimension(:), allocatable, save, public m_global::coulomb_i
Definition at line 10 of file m_global.f90.
coulomb_n
type(t_tensor4), dimension(:), allocatable, save, public m_global::coulomb_n
Definition at line 12 of file m_global.f90.
fock_f
integer(dp), dimension(:), allocatable, save, public m_global::fock_f
Definition at line 22 of file m_global.f90.
fock_i
integer(dp), dimension(:), allocatable, save, public m_global::fock_i
Definition at line 20 of file m_global.f90.
fock_n
integer(dp), dimension(:), allocatable, save, public m_global::fock_n
Definition at line 21 of file m_global.f90.
ham_csr
type (t_csr), dimension(:), allocatable, save, public m_global::ham_csr
Definition at line 25 of file m_global.f90.
hopping_i
type(t_tensor2), dimension(:), allocatable, save, public m_global::hopping_i
Definition at line 9 of file m_global.f90.
hopping_n
type(t_tensor2), dimension(:), allocatable, save, public m_global::hopping_n
Definition at line 11 of file m_global.f90.
krylov_alpha
real(dp), dimension(:), allocatable, save, public m_global::krylov_alpha
Definition at line 31 of file m_global.f90.
krylov_beta
real(dp), dimension(:), allocatable, save, public m_global::krylov_beta
Definition at line 32 of file m_global.f90.
tran_csr
type (t_csr), dimension(:), allocatable, save, public m_global::tran_csr
Definition at line 28 of file m_global.f90.
transop_rixs_f
type(t_tensor2), dimension(:), allocatable, save, public m_global::transop_rixs_f
Definition at line 17 of file m_global.f90.
transop_rixs_i
type(t_tensor2), dimension(:), allocatable, save, public m_global::transop_rixs_i
Definition at line 16 of file m_global.f90.
transop_xas
type(t_tensor2), dimension(:), allocatable, save, public m_global::transop_xas
Definition at line 15 of file m_global.f90.