Fotran EDRIXS: m_lanczos Module Reference
m_lanczos Module Reference
Functions/Subroutines
subroutine diag_ham_lanczos (nblock, end_indx, needed, nloc, nev, max_niter, eval_tol, ham, eval, n_vec, evec)
subroutine krylov_eigs (n, alpha, beta, eval, evec)
subroutine build_krylov_mp (nblock, end_indx, needed, nloc, ham, init_vec, maxn, neff, alpha, beta, norm)
subroutine build_spectrum (nkrylov, alpha, beta, norm, nw, om_mesh, e_gs, gamma_final, spec)
Function/Subroutine Documentation
build_krylov_mp()
subroutine m_lanczos::build_krylov_mp (integer, intent(in) nblock, integer, dimension(2,2,nprocs), intent(in) end_indx, integer, dimension(nprocs, nprocs), intent(in) needed, integer, intent(in) nloc, type (t_csr), dimension(nblock) ham, complex(dp), dimension(nloc), intent(in) init_vec, integer, intent(in) maxn, integer, intent(out) neff, real(dp), dimension(maxn), intent(out) alpha, real(dp), dimension(0:maxn), intent(out) beta, real(dp), intent(out) norm)
Definition at line 210 of file lanczos.f90.
References m_constants::czero, m_constants::dp, m_control::master, m_control::myid, m_constants::mystd, m_control::new_comm, m_control::nprocs, pspmv_csr(), and m_constants::zero.
build_spectrum()
subroutine m_lanczos::build_spectrum (integer, intent(in) nkrylov, real(dp), dimension(nkrylov), intent(in) alpha, real(dp), dimension(0:nkrylov), intent(in) beta, real(dp), intent(in) norm, integer, intent(in) nw, real(dp), dimension(nw), intent(in) om_mesh, real(dp), intent(in) e_gs, real(dp), dimension(nw), intent(in) gamma_final, real(dp), dimension(nw), intent(out) spec)
Definition at line 306 of file lanczos.f90.
References m_constants::czero, m_constants::dp, and m_constants::pi.
diag_ham_lanczos()
subroutine m_lanczos::diag_ham_lanczos (integer, intent(in) nblock, integer, dimension(2,2,nprocs), intent(in) end_indx, integer, dimension(nprocs, nprocs), intent(in) needed, integer, intent(in) nloc, integer, intent(in) nev, integer, intent(in) max_niter, real(dp), intent(in) eval_tol, type (t_csr), dimension(nblock) ham, real(dp), dimension(nev), intent(out) eval, integer, intent(in) n_vec, complex(dp), dimension(nloc,n_vec), intent(out) evec)
Definition at line 6 of file lanczos.f90.
References m_constants::czero, m_constants::dp, krylov_eigs(), m_control::master, m_control::myid, m_constants::mystd, m_control::new_comm, m_control::nprocs, pspmv_csr(), and m_constants::zero.
krylov_eigs()
subroutine m_lanczos::krylov_eigs (integer, intent(in) n, real(dp), dimension(n), intent(in) alpha, real(dp), dimension(n-1), intent(in) beta, real(dp), dimension(n), intent(out) eval, real(dp), dimension(n,n), intent(out) evec)
Definition at line 169 of file lanczos.f90.
References m_constants::dp, and m_constants::zero.