Fotran EDRIXS: opavg_main.f90 File Reference
opavg_main.f90 File Reference
Functions/Subroutines
program opavg_main
Function/Subroutine Documentation
opavg_main()
program opavg_main
Definition at line 1 of file opavg_main.f90.
References config(), m_global::dealloc_fock_i(), m_control::master, m_control::myid, m_control::ndim_i, m_control::new_comm, m_control::nprocs, opavg_driver(), m_control::origin_comm, m_control::origin_myid, m_control::origin_nprocs, and read_fock_i().