Fotran EDRIXS: opavg_driver.f90 File Reference
opavg_driver.f90 File Reference
Functions/Subroutines
subroutine opavg_driver ()
Function/Subroutine Documentation
opavg_driver()
subroutine opavg_driver
Definition at line 1 of file opavg_driver.f90.
References m_global::alloc_ham_csr(), build_ham_i(), m_global::coulomb_i, m_constants::czero, m_global::dealloc_fock_i(), m_global::fock_i, get_needed_indx(), get_number_nonzeros(), m_global::ham_csr, m_global::hopping_i, m_control::master, m_control::myid, m_constants::mystd, m_control::ncoul_i, m_control::ndim_i, m_control::new_comm, m_control::nhopp_i, m_control::num_val_orbs, partition_task(), pspmv_csr(), read_coulomb_i(), read_eigvecs(), read_fock_i(), read_hopping_i(), write_opavg(), and m_constants::zero.