Fotran EDRIXS: pyapi.f90 File Reference
pyapi.f90 File Reference
Functions/Subroutines
subroutine ed_fsolver (comm, my_id, num_procs)
subroutine xas_fsolver (comm, my_id, num_procs)
subroutine rixs_fsolver (comm, my_id, num_procs)
subroutine opavg_fsolver (comm, my_id, num_procs)
Function/Subroutine Documentation
ed_fsolver()
subroutine ed_fsolver (integer, intent(in) comm, integer, intent(in) my_id, integer, intent(in) num_procs)
Definition at line 1 of file pyapi.f90.
References config(), m_global::dealloc_fock_i(), ed_driver(), m_control::master, m_control::myid, m_control::ndim_i, m_control::new_comm, m_control::nprocs, m_control::origin_comm, m_control::origin_myid, m_control::origin_nprocs, and read_fock_i().
opavg_fsolver()
subroutine opavg_fsolver (integer, intent(in) comm, integer, intent(in) my_id, integer, intent(in) num_procs)
Definition at line 184 of file pyapi.f90.
References config(), m_global::dealloc_fock_i(), m_control::master, m_control::myid, m_control::ndim_i, m_control::new_comm, m_control::nprocs, opavg_driver(), m_control::origin_comm, m_control::origin_myid, m_control::origin_nprocs, and read_fock_i().
rixs_fsolver()
subroutine rixs_fsolver (integer, intent(in) comm, integer, intent(in) my_id, integer, intent(in) num_procs)
Definition at line 120 of file pyapi.f90.
References config(), m_global::dealloc_fock_f(), m_global::dealloc_fock_i(), m_global::dealloc_fock_n(), m_control::master, m_control::myid, m_control::ndim_f, m_control::ndim_i, m_control::ndim_n, m_control::ndim_n_nocore, m_control::new_comm, m_control::nprocs, m_control::num_core_orbs, m_control::origin_comm, m_control::origin_myid, m_control::origin_nprocs, read_fock_f(), read_fock_i(), read_fock_n(), and rixs_driver().
xas_fsolver()
subroutine xas_fsolver (integer, intent(in) comm, integer, intent(in) my_id, integer, intent(in) num_procs)
Definition at line 58 of file pyapi.f90.
References config(), m_global::dealloc_fock_i(), m_global::dealloc_fock_n(), m_control::master, m_control::myid, m_control::ndim_i, m_control::ndim_n, m_control::ndim_n_nocore, m_control::new_comm, m_control::nprocs, m_control::num_core_orbs, m_control::origin_comm, m_control::origin_myid, m_control::origin_nprocs, read_fock_i(), read_fock_n(), and xas_driver().