Fotran EDRIXS: rixs_main.f90 File Reference
rixs_main.f90 File Reference
Functions/Subroutines
program rixs_main
Function/Subroutine Documentation
rixs_main()
program rixs_main
Definition at line 1 of file rixs_main.f90.
References config(), m_global::dealloc_fock_f(), m_global::dealloc_fock_i(), m_global::dealloc_fock_n(), m_control::master, m_control::myid, m_control::ndim_f, m_control::ndim_i, m_control::ndim_n, m_control::ndim_n_nocore, m_control::new_comm, m_control::nprocs, m_control::num_core_orbs, m_control::origin_comm, m_control::origin_myid, m_control::origin_nprocs, read_fock_f(), read_fock_i(), read_fock_n(), and rixs_driver().