Fotran EDRIXS: rixs_driver.f90 File Reference
rixs_driver.f90 File Reference
Functions/Subroutines
subroutine rixs_driver ()
Function/Subroutine Documentation
rixs_driver()
subroutine rixs_driver
Definition at line 1 of file rixs_driver.f90.
References m_global::alloc_ham_csr(), m_global::alloc_tran_csr(), build_ham_i(), build_ham_n(), m_lanczos::build_krylov_mp(), build_transop_f(), build_transop_i(), m_global::coulomb_i, m_global::coulomb_n, m_constants::czero, m_global::dealloc_coulomb_i(), m_global::dealloc_coulomb_n(), m_global::dealloc_fock_f(), m_global::dealloc_fock_i(), m_global::dealloc_fock_n(), m_global::dealloc_ham_csr(), m_global::dealloc_hopping_i(), m_global::dealloc_hopping_n(), m_global::dealloc_tran_csr(), m_global::dealloc_transop_rixs_f(), m_global::dealloc_transop_rixs_i(), m_global::fock_f, m_global::fock_i, m_global::fock_n, m_control::gamma_in, get_needed_indx(), get_number_nonzeros(), m_global::ham_csr, m_global::hopping_i, m_global::hopping_n, m_global::krylov_alpha, m_global::krylov_beta, m_control::linsys_max, m_control::linsys_tol, m_control::master, m_control::myid, m_constants::mystd, m_control::ncoul_i, m_control::ncoul_n, m_control::ndim_f, m_control::ndim_i, m_control::ndim_n, m_control::ndim_n_nocore, m_control::new_comm, m_control::nhopp_i, m_control::nhopp_n, m_control::nkryl, m_control::ntran_rixs_f, m_control::ntran_rixs_i, m_control::num_core_orbs, m_control::num_gs, m_control::num_val_orbs, m_control::omega_in, partition_task(), pminres_csr(), pspmv_csr(), read_coulomb_i(), read_coulomb_n(), read_eigvecs(), read_fock_f(), read_fock_i(), read_fock_n(), read_hopping_i(), read_hopping_n(), read_transop_rixs_f(), read_transop_rixs_i(), m_global::tran_csr, m_global::transop_rixs_f, m_global::transop_rixs_i, write_krylov(), and m_constants::zero.