.TH "fock.f90" 3 "Sat Jun 10 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fock.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBcal_combination\fP (n, m, cnm)"
.br
.ti -1c
.RI "subroutine \fBmake_newfock\fP (c_type, pos, old, new, sgn)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine cal_combination (integer, intent(in) n, integer, intent(in) m, integer, intent(out) cnm)"
Subroutine cal_combination calculates $^nC_m $ 
.br
 Subroutine make_newfock evaluates \&.\&.\&.\&. 
.PP
Definition at line \fB4\fP of file \fBfock\&.f90\fP\&.
.SS "subroutine make_newfock (character(1), intent(in) c_type, integer, intent(in) pos, integer(dp), intent(in) old, integer(dp), intent(out) new, integer, intent(out) sgn)"

.PP
Definition at line \fB41\fP of file \fBfock\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
