.TH "full_diag.f90" 3 "Sat Jun 10 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
full_diag.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBfull_diag_ham\fP (ndim, ham, eval, evec)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine full_diag_ham (integer, intent(in) ndim, complex(dp), dimension(ndim, ndim), intent(in) ham, real(dp), dimension(ndim), intent(out) eval, complex(dp), dimension(ndim,ndim), intent(out) evec)"

.PP
Definition at line \fB1\fP of file \fBfull_diag\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
