.TH "m_constants.f90" 3 "Sat Jun 10 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_constants.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBm_constants\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter, public \fBm_constants::dp\fP = kind(1\&.0d0)"
.br
.ti -1c
.RI "integer, parameter, public \fBm_constants::mystd\fP = 6"
.br
.ti -1c
.RI "integer, parameter, public \fBm_constants::mytmp\fP = 100"
.br
.ti -1c
.RI "real(dp), parameter, public \fBm_constants::zero\fP = 0\&.0_dp"
.br
.ti -1c
.RI "real(dp), parameter, public \fBm_constants::one\fP = 1\&.0_dp"
.br
.ti -1c
.RI "real(dp), parameter, public \fBm_constants::pi\fP = 3\&.1415926535897932_dp"
.br
.ti -1c
.RI "complex(dp), parameter, public \fBm_constants::czi\fP = dcmplx(0\&.0_dp, 1\&.0_dp)"
.br
.ti -1c
.RI "complex(dp), parameter, public \fBm_constants::cone\fP = dcmplx(1\&.0_dp, 0\&.0_dp)"
.br
.ti -1c
.RI "complex(dp), parameter, public \fBm_constants::czero\fP = dcmplx(0\&.0_dp, 0\&.0_dp)"
.br
.ti -1c
.RI "real(dp), parameter, public \fBm_constants::ev2k\fP = 11604\&.505008098_dp"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
