.TH "m_constants" 3 "Sat Jun 10 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_constants
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter, public \fBdp\fP = kind(1\&.0d0)"
.br
.ti -1c
.RI "integer, parameter, public \fBmystd\fP = 6"
.br
.ti -1c
.RI "integer, parameter, public \fBmytmp\fP = 100"
.br
.ti -1c
.RI "real(\fBdp\fP), parameter, public \fBzero\fP = 0\&.0_dp"
.br
.ti -1c
.RI "real(\fBdp\fP), parameter, public \fBone\fP = 1\&.0_dp"
.br
.ti -1c
.RI "real(\fBdp\fP), parameter, public \fBpi\fP = 3\&.1415926535897932_dp"
.br
.ti -1c
.RI "complex(\fBdp\fP), parameter, public \fBczi\fP = dcmplx(0\&.0_dp, 1\&.0_dp)"
.br
.ti -1c
.RI "complex(\fBdp\fP), parameter, public \fBcone\fP = dcmplx(1\&.0_dp, 0\&.0_dp)"
.br
.ti -1c
.RI "complex(\fBdp\fP), parameter, public \fBczero\fP = dcmplx(0\&.0_dp, 0\&.0_dp)"
.br
.ti -1c
.RI "real(\fBdp\fP), parameter, public \fBev2k\fP = 11604\&.505008098_dp"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "complex(\fBdp\fP), parameter, public m_constants::cone = dcmplx(1\&.0_dp, 0\&.0_dp)"

.PP
Definition at line \fB13\fP of file \fBm_constants\&.f90\fP\&.
.SS "complex(\fBdp\fP), parameter, public m_constants::czero = dcmplx(0\&.0_dp, 0\&.0_dp)"

.PP
Definition at line \fB14\fP of file \fBm_constants\&.f90\fP\&.
.SS "complex(\fBdp\fP), parameter, public m_constants::czi = dcmplx(0\&.0_dp, 1\&.0_dp)"

.PP
Definition at line \fB12\fP of file \fBm_constants\&.f90\fP\&.
.SS "integer, parameter, public m_constants::dp = kind(1\&.0d0)"

.PP
Definition at line \fB4\fP of file \fBm_constants\&.f90\fP\&.
.SS "real(\fBdp\fP), parameter, public m_constants::ev2k = 11604\&.505008098_dp"

.PP
Definition at line \fB16\fP of file \fBm_constants\&.f90\fP\&.
.SS "integer, parameter, public m_constants::mystd = 6"

.PP
Definition at line \fB5\fP of file \fBm_constants\&.f90\fP\&.
.SS "integer, parameter, public m_constants::mytmp = 100"

.PP
Definition at line \fB6\fP of file \fBm_constants\&.f90\fP\&.
.SS "real(\fBdp\fP), parameter, public m_constants::one = 1\&.0_dp"

.PP
Definition at line \fB9\fP of file \fBm_constants\&.f90\fP\&.
.SS "real(\fBdp\fP), parameter, public m_constants::pi = 3\&.1415926535897932_dp"

.PP
Definition at line \fB10\fP of file \fBm_constants\&.f90\fP\&.
.SS "real(\fBdp\fP), parameter, public m_constants::zero = 0\&.0_dp"

.PP
Definition at line \fB8\fP of file \fBm_constants\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
