.TH "m_control.f90" 3 "Sat Jun 10 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_control.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBm_control\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save, public \fBm_control::ed_solver\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::num_val_orbs\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::num_core_orbs\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ndim_i\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ndim_n_nocore\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ndim_n\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ndim_f\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::nhopp_i\fP =1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ncoul_i\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::nhopp_n\fP =1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ncoul_n\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ntran_xas\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ntran_rixs_i\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ntran_rixs_f\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::neval\fP = 1"
.br
.ti -1c
.RI "logical, save, public \fBm_control::idump\fP = \&.false\&."
.br
.ti -1c
.RI "integer, save, public \fBm_control::nvector\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::num_gs\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::maxiter\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::linsys_max\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::min_ndim\fP = 100"
.br
.ti -1c
.RI "integer, save, public \fBm_control::ncv\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::nkryl\fP = 500"
.br
.ti -1c
.RI "real(dp), save, public \fBm_control::eigval_tol\fP = 1E\-10"
.br
.ti -1c
.RI "real(dp), save, public \fBm_control::linsys_tol\fP = 1E\-12"
.br
.ti -1c
.RI "real(dp), save, public \fBm_control::omega_in\fP"
.br
.ti -1c
.RI "real(dp), save, public \fBm_control::gamma_in\fP"
.br
.ti -1c
.RI "integer, save, public \fBm_control::origin_nprocs\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::nprocs\fP = 1"
.br
.ti -1c
.RI "integer, save, public \fBm_control::origin_myid\fP = 0"
.br
.ti -1c
.RI "integer, save, public \fBm_control::myid\fP = 0"
.br
.ti -1c
.RI "integer, save, public \fBm_control::master\fP = 0"
.br
.ti -1c
.RI "integer, save, public \fBm_control::new_comm\fP = 0"
.br
.ti -1c
.RI "integer, save, public \fBm_control::origin_comm\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
