.TH "m_types::t_container_col" 3 "Sat Jun 10 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_types::t_container_col
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "type(\fBt_col\fP), pointer \fBcol_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB33\fP of file \fBm_types\&.f90\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "type (\fBt_col\fP), pointer m_types::t_container_col::col_ptr"

.PP
Definition at line \fB35\fP of file \fBm_types\&.f90\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
