.TH "m_types::t_csr" 3 "Sat Jun 10 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m_types::t_csr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBnnz\fP"
.br
.ti -1c
.RI "integer \fBm\fP"
.br
.ti -1c
.RI "integer \fBrow_shift\fP"
.br
.ti -1c
.RI "integer \fBcol_shift\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable \fBiaa\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable \fBjaa\fP"
.br
.ti -1c
.RI "complex(dp), dimension(:), allocatable \fBaa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB39\fP of file \fBm_types\&.f90\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "complex(dp), dimension(:), allocatable m_types::t_csr::aa"

.PP
Definition at line \fB53\fP of file \fBm_types\&.f90\fP\&.
.SS "integer m_types::t_csr::col_shift"

.PP
Definition at line \fB47\fP of file \fBm_types\&.f90\fP\&.
.SS "integer, dimension(:), allocatable m_types::t_csr::iaa"

.PP
Definition at line \fB49\fP of file \fBm_types\&.f90\fP\&.
.SS "integer, dimension(:), allocatable m_types::t_csr::jaa"

.PP
Definition at line \fB51\fP of file \fBm_types\&.f90\fP\&.
.SS "integer m_types::t_csr::m"

.PP
Definition at line \fB43\fP of file \fBm_types\&.f90\fP\&.
.SS "integer m_types::t_csr::nnz"

.PP
Definition at line \fB41\fP of file \fBm_types\&.f90\fP\&.
.SS "integer m_types::t_csr::row_shift"

.PP
Definition at line \fB45\fP of file \fBm_types\&.f90\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
