.TH "pyapi.f90" 3 "Sat Jun 10 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pyapi.f90
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBed_fsolver\fP (comm, my_id, num_procs)"
.br
.ti -1c
.RI "subroutine \fBxas_fsolver\fP (comm, my_id, num_procs)"
.br
.ti -1c
.RI "subroutine \fBrixs_fsolver\fP (comm, my_id, num_procs)"
.br
.ti -1c
.RI "subroutine \fBopavg_fsolver\fP (comm, my_id, num_procs)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ed_fsolver (integer, intent(in) comm, integer, intent(in) my_id, integer, intent(in) num_procs)"

.PP
Definition at line \fB1\fP of file \fBpyapi\&.f90\fP\&.
.SS "subroutine opavg_fsolver (integer, intent(in) comm, integer, intent(in) my_id, integer, intent(in) num_procs)"

.PP
Definition at line \fB184\fP of file \fBpyapi\&.f90\fP\&.
.SS "subroutine rixs_fsolver (integer, intent(in) comm, integer, intent(in) my_id, integer, intent(in) num_procs)"

.PP
Definition at line \fB120\fP of file \fBpyapi\&.f90\fP\&.
.SS "subroutine xas_fsolver (integer, intent(in) comm, integer, intent(in) my_id, integer, intent(in) num_procs)"

.PP
Definition at line \fB58\fP of file \fBpyapi\&.f90\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
